name: Build check
on:
  push:
    branches:
      - master
      - main
      - CI
  pull_request:
    branches:
      - master
      - main
      - CI
jobs:
  build:
    name: Build check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            vcpkg-bootstap-cmd: .\vcpkg\bootstrap-vcpkg.bat
            toolchain-file: ./vcpkg/scripts/buildsystems/vcpkg.cmake

          - os: ubuntu-latest
            vcpkg-bootstap-cmd: ./vcpkg/bootstrap-vcpkg.sh
            toolchain-file: ./vcpkg/scripts/buildsystems/vcpkg.cmake
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install VCPKG
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          ${{ matrix.vcpkg-bootstap-cmd }}
      
      - name: Download dependencies
        working-directory: build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain-file }} ..
        
      - name: Build
        run: cmake --build .
        working-directory: build
        